#!/usr/bin/env python3
"""
update_activity_log.py

A small, idempotent-ish script intended to be run once per day by a
GitHub Actions workflow. It appends a timestamped entry to a plain-text
log file (activity_log.md) at the repository root.

Design goals:
  - No external dependencies (stdlib only) so it runs anywhere Python 3 runs.
  - Safe to re-run: if it's already been run today, it won't create a
    duplicate entry for the same date (helps avoid multiple commits if a
    workflow is accidentally triggered twice in one day).
  - Clear, human-readable output so the log file itself is mildly useful
    (e.g., you could jot a one-line "what I worked on" note here manually
    too, if you want it to double as a simple daily journal).

Exit codes:
  0 - Success (either a new entry was added, or one already existed today)
  1 - Unexpected error
"""

import datetime
import pathlib
import sys

# Path to the log file, relative to the repository root.
# The GitHub Actions workflow runs this script from the repo root,
# so a relative path works correctly there.
LOG_FILE = pathlib.Path("activity_log.md")

# Header written once at the top of a brand-new log file.
FILE_HEADER = "# Activity Log\n\nAutomated daily entries generated by GitHub Actions.\n\n"


def get_today_str() -> str:
    """Return today's date in ISO format (UTC), e.g. '2026-09-08'."""
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")


def get_timestamp_str() -> str:
    """Return the full current UTC timestamp for the log entry."""
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def already_logged_today(today_str: str) -> bool:
    """
    Check whether today's date already has an entry in the log file.
    Prevents duplicate entries if the script runs more than once in a day.
    """
    if not LOG_FILE.exists():
        return False
    contents = LOG_FILE.read_text(encoding="utf-8")
    return f"- {today_str}" in contents


def main() -> int:
    try:
        today_str = get_today_str()

        if already_logged_today(today_str):
            print(f"[update_activity_log] Entry for {today_str} already exists. Skipping.")
            return 0

        # Create the file with a header if it doesn't exist yet.
        if not LOG_FILE.exists():
            LOG_FILE.write_text(FILE_HEADER, encoding="utf-8")

        entry = f"- {today_str} — updated at {get_timestamp_str()}\n"

        with LOG_FILE.open("a", encoding="utf-8") as f:
            f.write(entry)

        print(f"[update_activity_log] Added entry: {entry.strip()}")
        return 0

    except Exception as exc:  # Fail loudly but gracefully in CI logs.
        print(f"[update_activity_log] ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
